# Generated by Django 3.0.8 on 2020-07-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('description', models.TextField(verbose_name='Task description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_process', 'In process'), ('resolved', 'Resolved')], default='Open', max_length=10, verbose_name='Task status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('now', 'Now')], max_length=6, verbose_name='Task priority')),
            ],
            options={
                'verbose_name': 'Task',
                'ordering': ['-due_date'],
            },
        ),
    ]
