# Generated by Django 3.0.8 on 2020-07-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name': 'Task'},
        ),
    ]
